#!/bin/bash

set -e  # stop on error

WORK_TREE=/home/yourcpaneluser/public_html
GIT_DIR=/home/yourcpaneluser/repositories/your-repo.git

while read oldrev newrev ref
do
  if [ "$ref" = "refs/heads/main" ]; then
    git --work-tree="$WORK_TREE" --git-dir="$GIT_DIR" checkout -f
  fi
done